name: flutrofit_generator
description: Rest API generator for flutter like Retrofit
repository: https://github.com/sglim/flutrofit
version: 0.1.0

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: ">=0.12.0 <2.0.0"
  source_gen: ^0.9.0
  flutrofit: ^0.1.0
  analyzer: ^0.32.0

dev_dependencies:
  build_test: ^0.10.0
  build_runner: ">=0.9.0 <0.11.0"
  test: ^1.0.0
